#!/bin/sh

# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

VENDOR=lge
DEVICE=lu2300

mkdir -p ../../../vendor/$VENDOR/$DEVICE

(cat << EOF) | sed s/__DEVICE__/$DEVICE/g | sed s/__VENDOR__/$VENDOR/g > ../../../vendor/$VENDOR/$DEVICE/$DEVICE-vendor.mk
# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/__VENDOR__/__DEVICE__/setup-makefiles.sh

# Live wallpaper packages
PRODUCT_PACKAGES := \\
    LiveWallpapers \\
    LiveWallpapersPicker \\
    VisualizationWallpapers \\
    librs_jni

\$(call inherit-product, vendor/__VENDOR__/__DEVICE__/__DEVICE__-vendor-blobs.mk)
EOF

(cat << EOF) | sed s/__DEVICE__/$DEVICE/g | sed s/__VENDOR__/$VENDOR/g > ../../../vendor/$VENDOR/$DEVICE/$DEVICE-vendor-blobs.mk
# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/__VENDOR__/__DEVICE__/setup-makefiles.sh

# HAL
PRODUCT_COPY_FILES += \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/hw/gralloc.default.so:obj/lib/gralloc.default.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/hw/gralloc.default.so:system/lib/hw/gralloc.default.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/hw/gralloc.qsd8k.so:obj/lib/gralloc.qsd8k.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/hw/gralloc.qsd8k.so:system/lib/hw/gralloc.qsd8k.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/liblgosp-hal.so:system/lib/liblgosp-hal.so

# 3D
PRODUCT_COPY_FILES += \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/etc/firmware/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \\
    vendor/__VENDOR__/__DEVICE__/proprietary/etc/firmware/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libgsl.so:system/lib/libgsl.so

# Sensor
PRODUCT_COPY_FILES += \\
    vendor/__VENDOR__/__DEVICE__/proprietary/bin/akmd2:system/bin/akmd2

# Wifi
PRODUCT_COPY_FILES += \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/modules/wireless.ko:system/lib/modules/wireless.ko \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libnetutils.so:obj/lib/libnetutils.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libnetutils.so:system/lib/libnetutils.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/etc/wl/nvram.txt:system/etc/wl/nvram.txt \\
    vendor/__VENDOR__/__DEVICE__/proprietary/etc/wl/rtecdc-apsta.bin:system/etc/wl/rtecdc-apsta.bin \\
    vendor/__VENDOR__/__DEVICE__/proprietary/etc/wl/rtecdc-mfgtest.bin:system/etc/wl/rtecdc-mfgtest.bin \\
    vendor/__VENDOR__/__DEVICE__/proprietary/etc/wl/rtecdc.bin:system/etc/wl/rtecdc.bin \\
    vendor/__VENDOR__/__DEVICE__/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \\
    vendor/__VENDOR__/__DEVICE__/proprietary/etc/dhcpcd/dhcpcd.conf:system/etc/dhcpcd/dhcpcd.conf \\
    vendor/__VENDOR__/__DEVICE__/proprietary/bin/dhd:system/bin/dhd \\
    vendor/__VENDOR__/__DEVICE__/proprietary/bin/iperf:system/bin/iperf \\
    vendor/__VENDOR__/__DEVICE__/proprietary/bin/wl:system/bin/wl

# Bluetoooth
PRODUCT_COPY_FILES += \\
    vendor/__VENDOR__/__DEVICE__/proprietary/bin/BCM4325D1_004.002.004.0262.0275.hcd:system/bin/BCM4325D1_004.002.004.0262.0275.hcd

# Camera
PRODUCT_COPY_FILES += \\
    vendor/__VENDOR__/__DEVICE__/proprietary/media/camera/fw/CE14XF00.bin:system/media/camera/fw/CE14XF00.bin \\
    vendor/__VENDOR__/__DEVICE__/proprietary/media/camera/fw/CE14XF01.bin:system/media/camera/fw/CE14XF01.bin \\
    vendor/__VENDOR__/__DEVICE__/proprietary/media/camera/fw/CE14XF02.bin:system/media/camera/fw/CE14XF02.bin \\
    vendor/__VENDOR__/__DEVICE__/proprietary/media/camera/fw/CE14XF03.bin:system/media/camera/fw/CE14XF03.bin \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libcamera.so:obj/lib/libcamera.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libcamera.so:system/lib/libcamera.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libcameraservice.so:obj/lib/libcameraservice.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libcameraservice.so:system/lib/libcameraservice.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libcamera_client.so:obj/lib/libcamera_client.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libcamera_client.so:system/lib/libcamera_client.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libOlaCameraJNI.so:system/lib/libOlaCameraJNI.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libOlaEngine.so:system/lib/libOlaEngine.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libOlaFrameResource.so:system/lib/libOlaFrameResource.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libOlaImageEditorJNI.so:system/lib/libOlaImageEditorJNI.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libola_pixel_utils.so:system/lib/libola_pixel_utils.so

# QSOUND
#PRODUCT_COPY_FILES += \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/etc/qsound/mQ256-v44se.dls:system/etc/qsound/mQ256-v44se.dls \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/etc/qsound/mQ512-v44as.dls:system/etc/qsound/mQ512-v44as.dls \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/etc/qsound/mQ512-v44se.dls:system/etc/qsound/mQ512-v44se.dls

# Permissions
PRODUCT_COPY_FILES += \\
    vendor/__VENDOR__/__DEVICE__/proprietary/etc/permissions/android.software.live_wallpaper.xml:system/etc/permissions/android.software.live_wallpaper.xml \\
    vendor/__VENDOR__/__DEVICE__/proprietary/etc/permissions/com.nextreaming.AudioEffectManager.xml:system/etc/permissions/com.nextreaming.AudioEffectManager.xml \\
    vendor/__VENDOR__/__DEVICE__/proprietary/etc/permissions/com.nextreaming.NexSubtitle.xml:system/etc/permissions/com.nextreaming.NexSubtitle.xml \\
    vendor/__VENDOR__/__DEVICE__/proprietary/etc/permissions/com.qualcomm.location.vzw_library.xml:system/etc/permissions/com.qualcomm.location.vzw_library.xml

# LGE services
PRODUCT_COPY_FILES += \\
    vendor/__VENDOR__/__DEVICE__/proprietary/bin/qmuxd:system/bin/qmuxd

# rmt_storage (What is this?)
#PRODUCT_COPY_FILES += \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/bin/rmt_storage:system/bin/rmt_storage

# port-bridge (What is this?)
#PRODUCT_COPY_FILES += \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/bin/port-bridge:system/bin/port-bridge

# wipeirface (What is this?)
#PRODUCT_COPY_FILES += \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/bin/wiperiface:system/bin/wiperiface

# netmgr (What is this?)
#PRODUCT_COPY_FILES += \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/bin/netmgrd:system/bin/netmgrd \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so

# CKPD-daemon (What is this?)
#PRODUCT_COPY_FILES += \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/bin/CKPD-daemon:system/bin/CKPD-daemon

# RIL
PRODUCT_COPY_FILES += \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libril.so:system/lib/libril.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libril-qc-1.so:system/lib/libril-qc-1.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libpbmlib.so:system/lib/libpbmlib.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libpdapi.so:system/lib/libpdapi.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libpdsm_atl.so:system/lib/libpdsm_atl.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libqueue.so:system/lib/libqueue.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libnv.so:system/lib/libnv.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/liboem_rapi.so:system/lib/liboem_rapi.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libdsm.so:system/lib/libdsm.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libdiag.so:system/lib/libdiag.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libauth.so:system/lib/libauth.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libcm.so:system/lib/libcm.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libwms.so:system/lib/libwms.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libwmsts.so:system/lib/libwmsts.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libmmgsdilib.so:system/lib/libmmgsdilib.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libgsdi_exp.so:system/lib/libgsdi_exp.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libgstk_exp.so:system/lib/libgstk_exp.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libqmi.so:system/lib/libqmi.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libdll.so:system/lib/libdll.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libbcmwl.so:system/lib/libbcmwl.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libdss.so:system/lib/libdss.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libqcomm_omx.so:system/lib/libqcomm_omx.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libping_apps.so:system/lib/libping_apps.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libping_mdm.so:system/lib/libping_mdm.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libhardware_legacy.so:obj/lib/libhardware_legacy.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libhardware_legacy.so:system/lib/libhardware_legacy.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libcommondefs.so:system/lib/libcommondefs.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libloc-rpc.so:system/lib/libloc-rpc.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libloc.so:system/lib/libloc.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/bin/rild:system/bin/rild

# NEXTREAMING
#PRODUCT_COPY_FILES += \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libnextreaming_divx_drm16_service.so:system/lib/libnextreaming_divx_drm16_service.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libnextreaming_drm16.so:system/lib/libnextreaming_drm16.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libnextreaming_source_node.so:system/lib/libnextreaming_source_node.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libnextreaming_source_node_reg.so:system/lib/libnextreaming_source_node_reg.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libnextreaming_subtitle_jni.so:system/lib/libnextreaming_subtitle_jni.so
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libomx_nextreaming_ac3dec_sharedlibrary.so:system/lib/libomx_nextreaming_ac3dec_sharedlibrary.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libomx_nextreaming_bsacdec_sharedlibrary.so:system/lib/libomx_nextreaming_bsacdec_sharedlibrary.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libomx_nextreaming_divxdec_sharedlibrary.so:system/lib/libomx_nextreaming_divxdec_sharedlibrary.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libomx_nextreaming_musicamdec_sharedlibrary.so:system/lib/libomx_nextreaming_musicamdec_sharedlibrary.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libomx_nextreaming_wmadec_sharedlibrary.so:system/lib/libomx_nextreaming_wmadec_sharedlibrary.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libomx_nextreaming_wmvdec_sharedlibrary.so:system/lib/libomx_nextreaming_wmvdec_sharedlibrary.so

# OMX
PRODUCT_COPY_FILES += \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libOmxAacDec.so:system/lib/libOmxAacDec.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libOmxAacEnc.so:system/lib/libOmxAacEnc.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libOmxAmrEnc.so:system/lib/libOmxAmrEnc.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libOmxEvrcDec.so:system/lib/libOmxEvrcDec.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libOmxEvrcEnc.so:system/lib/libOmxEvrcEnc.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libOmxMp3Dec.so:system/lib/libOmxMp3Dec.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libOmxQcelp13Dec.so:system/lib/libOmxQcelp13Dec.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libOmxQcelp13Enc.so:system/lib/libOmxQcelp13Enc.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libOmxVdec.so:system/lib/libOmxVdec.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libOmxCore.so:system/lib/libOmxCore.so

# OMX sharedlib
#PRODUCT_COPY_FILES += \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libomx_sharedlibrary.so:system/lib/libomx_sharedlibrary.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libomx_aacdec_sharedlibrary.so:system/lib/libomx_aacdec_sharedlibrary.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libomx_amrdec_sharedlibrary.so:system/lib/libomx_amrdec_sharedlibrary.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libomx_amrenc_sharedlibrary.so:system/lib/libomx_amrenc_sharedlibrary.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libomx_avcdec_sharedlibrary.so:system/lib/libomx_avcdec_sharedlibrary.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libomx_m4vdec_sharedlibrary.so:system/lib/libomx_m4vdec_sharedlibrary.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libomx_mp3dec_sharedlibrary.so:system/lib/libomx_mp3dec_sharedlibrary.so

# MM
#PRODUCT_COPY_FILES += \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libmm-omxcore.so:system/lib/libmm-omxcore.so

# OMX BIN
#PRODUCT_COPY_FILES += \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/bin/mm-abl-test:system/bin/mm-abl-test \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/bin/mm-adec-omxaac-test:system/bin/mm-adec-omxaac-test \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/bin/mm-adec-omxevrc-test:system/bin/mm-adec-omxevrc-test \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/bin/mm-adec-omxmp3-test:system/bin/mm-adec-omxmp3-test \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/bin/mm-adec-omxQcelp13-test:system/bin/mm-adec-omxQcelp13-test \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/bin/mm-aenc-omxaac-test:system/bin/mm-aenc-omxaac-test \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/bin/mm-aenc-omxamr-test:system/bin/mm-aenc-omxamr-test \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/bin/mm-aenc-omxevrc-test:system/bin/mm-aenc-omxevrc-test \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/bin/mm-audio-native-test:system/bin/mm-audio-native-test \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/bin/mm-jpeg-dec-test:system/bin/mm-jpeg-dec-test \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/bin/mm-jpeg-enc-test:system/bin/mm-jpeg-enc-test \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/bin/mm-qcamera-test:system/bin/mm-qcamera-test \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/bin/mm-qcamera-testsuite-client:system/bin/mm-qcamera-testsuite-client \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/bin/mm-vdec-omx-property-mgr:system/bin/mm-vdec-omx-property-mgr \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/bin/mm-venc-omx-test:system/bin/mm-venc-omx-test
#    vendor/__VENDOR__/__DEVICE__/proprietary/bin/mm-vdec-omx-test:system/bin/mm-vdec-omx-test \\

# Opencore
#PRODUCT_COPY_FILES += \\
#   vendor/__VENDOR__/__DEVICE__/proprietary/lib/libopencorehw.so:system/lib/libopencorehw.so \\
#   vendor/__VENDOR__/__DEVICE__/proprietary/lib/libopencore_author.so:system/lib/libopencore_author.so \\
#   vendor/__VENDOR__/__DEVICE__/proprietary/lib/libopencore_common.so:system/lib/libopencore_common.so \\
#   vendor/__VENDOR__/__DEVICE__/proprietary/lib/libopencore_downloadreg.so:system/lib/libopencore_downloadreg.so \\
#   vendor/__VENDOR__/__DEVICE__/proprietary/lib/libopencore_download.so:system/lib/libopencore_download.so \\
#   vendor/__VENDOR__/__DEVICE__/proprietary/lib/libopencore_mp4localreg.so:system/lib/libopencore_mp4localreg.so \\
#   vendor/__VENDOR__/__DEVICE__/proprietary/lib/libopencore_mp4local.so:system/lib/libopencore_mp4local.so \\
#   vendor/__VENDOR__/__DEVICE__/proprietary/lib/libopencore_net_support.so:system/lib/libopencore_net_support.so \\
#   vendor/__VENDOR__/__DEVICE__/proprietary/lib/libopencore_player.so:system/lib/libopencore_player.so \\
#   vendor/__VENDOR__/__DEVICE__/proprietary/lib/libopencore_rtspreg.so:system/lib/libopencore_rtspreg.so \\
#   vendor/__VENDOR__/__DEVICE__/proprietary/lib/libopencore_rtsp.so:system/lib/libopencore_rtsp.so


# Q3 LIB ?
#PRODUCT_COPY_FILES += \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libq3di32.so:system/lib/libq3di32.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libqchain32.so:system/lib/libqchain32.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libqnr32.so:system/lib/libqnr32.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libmqcore32.so:system/lib/libmqcore32.so

# DioDict
PRODUCT_COPY_FILES += \\
    vendor/__VENDOR__/__DEVICE__/proprietary/app/DioDict.apk:system/app/DioDict.apk \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libDioDictEngineNative.so:system/lib/libDioDictEngineNative.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libdhwr.so:system/lib/libdhwr.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libpowertts-jni.so:system/lib/libpowertts-jni.so

# Quickoffice
PRODUCT_COPY_FILES += \\
    vendor/__VENDOR__/__DEVICE__/proprietary/app/Quickoffice.apk:system/app/Quickoffice.apk \\

# Key
PRODUCT_COPY_FILES += \\
    vendor/__VENDOR__/__DEVICE__/proprietary/usr/keychars/lgosp-hid.kcm.bin:system/usr/keychars/lgosp-hid.kcm.bin \\
    vendor/__VENDOR__/__DEVICE__/proprietary/usr/keychars/pp2106_qwerty.kcm.bin:system/usr/keychars/pp2106_qwerty.kcm.bin \\
    vendor/__VENDOR__/__DEVICE__/proprietary/usr/keychars/surf_keypad.kcm.bin:system/usr/keychars/surf_keypad.kcm.bin \\
    vendor/__VENDOR__/__DEVICE__/proprietary/usr/keychars/surf_keypad.kcm.bin:system/usr/keychars/8k_handset.kcm.bin \\
    vendor/__VENDOR__/__DEVICE__/proprietary/usr/keychars/synaptics-rmi-touchscreen.kcm.bin:system/usr/keychars/synaptics-rmi-touchscreen.kcm.bin \\
    vendor/__VENDOR__/__DEVICE__/proprietary/usr/keylayout/lgosp-hid.kl:system/usr/keylayout/lgosp-hid.kl
#    vendor/__VENDOR__/__DEVICE__/proprietary/usr/keylayout/8k_handset.kl:system/usr/keylayout/8k_handset.kl \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/usr/keylayout/surf_keypad.kl:system/usr/keylayout/surf_keypad.kl

# Hangul IME
PRODUCT_COPY_FILES += \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libHangulCore.so:system/lib/libHangulCore.so

# Message
#PRODUCT_COPY_FILES += \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/app/Message.apk:system/app/Message.apk \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/fonts/LG_Android_SMS.ttf:system/fonts/LG_Android_SMS.ttf

# TDMB
PRODUCT_COPY_FILES += \\
    vendor/__VENDOR__/__DEVICE__/proprietary/app/TDMB.apk:system/app/TDMB.apk \\
    vendor/__VENDOR__/__DEVICE__/proprietary/bin/TdmbDiag:system/bin/TdmbDiag \\
    vendor/__VENDOR__/__DEVICE__/proprietary/bin/libbroadcast_server:system/bin/libbroadcast_server

# Etc
PRODUCT_COPY_FILES += \\
     vendor/__VENDOR__/__DEVICE__/proprietary/etc/01_qcomm_omx.cfg:system/etc/01_qcomm_omx.cfg \\
     vendor/__VENDOR__/__DEVICE__/proprietary/etc/vold.fstab:system/etc/vold.fstab \\
     vendor/__VENDOR__/__DEVICE__/proprietary/etc/apns-conf.xml:system/etc/apns-conf.xml \\
     vendor/__VENDOR__/__DEVICE__/proprietary/etc/pvplayer.cfg:system/etc/pvplayer.cfg \\
     vendor/__VENDOR__/__DEVICE__/proprietary/etc/init.qcom.bt.sh:system/etc/init.qcom.bt.sh \\
     vendor/__VENDOR__/__DEVICE__/proprietary/etc/init.qcom.coex.sh:system/etc/init.qcom.coex.sh \\
     vendor/__VENDOR__/__DEVICE__/proprietary/etc/init.qcom.fm.sh:system/etc/init.qcom.fm.sh \\
     vendor/__VENDOR__/__DEVICE__/proprietary/etc/init.qcom.post_boot.sh:system/etc/init.qcom.post_boot.sh \\
     vendor/__VENDOR__/__DEVICE__/proprietary/etc/init.qcom.sdio.sh:system/etc/init.qcom.sdio.sh

# LG OSP
#PRODUCT_COPY_FILES += \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/bin/lgospd_hid:system/bin/lgospd_hid \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/bin/lgospd:system/bin/lgospd \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/liblgosp.so:system/lib/liblgosp.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/modules/lgosp-hid.ko:system/lib/modules/lgosp-hid.ko

# LGE LIB
PRODUCT_COPY_FILES += \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/liblgedrmutil.so:system/lib/liblgedrmutil.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/liblge_modem_apis.so:system/lib/liblge_modem_apis.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/liblgerft.so:system/lib/liblgerft.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/liblgt_browser.so:system/lib/liblgt_browser.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/liblgt_downloader.so:system/lib/liblgt_downloader.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/liblgtomadrm.so:system/lib/liblgtomadrm.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libbroadcast_frame.so:system/lib/libbroadcast_frame.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libbroadcast_service.so:system/lib/libbroadcast_service.so \\
    vendor/__VENDOR__/__DEVICE__/proprietary/lib/liblgt_system.so:system/lib/liblgt_system.so

# LGE ETC LIB
#PRODUCT_COPY_FILES += \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libPowerDSR.so:system/lib/libPowerDSR.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libdrmlinker.so:system/lib/libdrmlinker.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libdslgapi.so:system/lib/libdslgapi.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libdsprofile.so:system/lib/libdsprofile.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libdigicapsdrm.so:system/lib/libdigicapsdrm.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libdigicapsdrm_rec.so:system/lib/libdigicapsdrm_rec.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libARMPlatform.so:system/lib/libARMPlatform.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libARMService.so:system/lib/libARMService.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libsis20plus.so:system/lib/libsis20plus.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libsis20plus_LGEdrv.so:system/lib/libsis20plus_LGEdrv.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libgcnative.so:system/lib/libgcnative.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libimsservice.so:system/lib/libimsservice.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libmlobex.so:system/lib/libmlobex.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libmm-abl.so:system/lib/libmm-abl.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libwiperjni.so:system/lib/libwiperjni.so
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libuvcm_jni.so:system/lib/libuvcm_jni.so \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/lib/libmm-omxcore.so:system/lib/libmm-omxcore.so \\

# LGE ETC BIN
#PRODUCT_COPY_FILES += \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/bin/diag_klog:system/bin/diag_klog \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/bin/diag_mdlog:system/bin/diag_mdlog \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/bin/handset-keypress:system/bin/handset-keypress \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/bin/nl_listener:system/bin/nl_listener \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/bin/rft:system/bin/rft \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/bin/rft.sh:system/bin/rft.sh \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/bin/mtc:system/bin/mtc \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/bin/eta:system/bin/eta \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/bin/event_monitor:system/bin/event_monitor \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/bin/PktRspTest:system/bin/PktRspTest \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/bin/lgesystemd:system/bin
#    vendor/__VENDOR__/__DEVICE__/proprietary/bin/lgesystemd_boot:system/bin

# LGE APPS
PRODUCT_COPY_FILES += \\
    vendor/__VENDOR__/__DEVICE__/proprietary/app/LGTARMService.apk:system/app/LGTARMService.apk \\
    vendor/__VENDOR__/__DEVICE__/proprietary/app/ContentsManager.apk:system/app/ContentsManager.apk \\
    vendor/__VENDOR__/__DEVICE__/proprietary/app/WipiPlayer.apk:system/app/WipiPlayer.apk
#    vendor/__VENDOR__/__DEVICE__/proprietary/app/AndroidBrowser.apk:system/app/AndroidBrowser.apk \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/app/AndroidDownloader.apk:system/app/AndroidDownloader.apk \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/app/CommonService.apk:system/app/CommonService.apk \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/app/ImsProvider.apk:system/app/ImsProvider.apk \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/app/HiddenMenuKorea.apk:system/app/HiddenMenuKorea.apk \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/app/LGCommon.apk:system/app/LGCommon.apk \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/app/LGTService.apk:system/app/LGTService.apk \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/app/LGTServiceProvider.apk:system/app/LGTServiceProvider.apk \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/app/LGVideoPlayer.apk:system/app/LGVideoPlayer.apk \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/app/OZStore.apk:system/app/OZStore.apk \\
#    vendor/__VENDOR__/__DEVICE__/proprietary/app/LGOnScreenPhone.apk:system/app/LGOnScreenPhone.apk \\

EOF

(cat << EOF) | sed s/__DEVICE__/$DEVICE/g | sed s/__VENDOR__/$VENDOR/g > ../../../vendor/$VENDOR/$DEVICE/BoardConfigVendor.mk
# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/__VENDOR__/__DEVICE__/setup-makefiles.sh

USE_CAMERA_STUB := false
EOF

